# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#

stages:
  - build

build-job:
  image: texlive/texlive
  stage: build
  script:
    - pdflatex "\newcommand{\CompanyName}{?\;} \input{resume-en.tex}"
  artifacts:
    paths:
      - resume-en.pdf
    when: on_success
    expire_in: 30 days